/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as LupoDiMareRouteImport } from './routes/lupo-di-mare'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as DjNovaRouteImport } from './routes/dj-nova'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LupoDiMareRoute = LupoDiMareRouteImport.update({
  id: '/lupo-di-mare',
  path: '/lupo-di-mare',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DjNovaRoute = DjNovaRouteImport.update({
  id: '/dj-nova',
  path: '/dj-nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dj-nova': typeof DjNovaRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/lupo-di-mare': typeof LupoDiMareRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dj-nova': typeof DjNovaRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/lupo-di-mare': typeof LupoDiMareRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dj-nova': typeof DjNovaRoute
  '/experience': typeof ExperienceRoute
  '/faq': typeof FaqRoute
  '/lupo-di-mare': typeof LupoDiMareRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dj-nova'
    | '/experience'
    | '/faq'
    | '/lupo-di-mare'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dj-nova'
    | '/experience'
    | '/faq'
    | '/lupo-di-mare'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dj-nova'
    | '/experience'
    | '/faq'
    | '/lupo-di-mare'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DjNovaRoute: typeof DjNovaRoute
  ExperienceRoute: typeof ExperienceRoute
  FaqRoute: typeof FaqRoute
  LupoDiMareRoute: typeof LupoDiMareRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupo-di-mare': {
      id: '/lupo-di-mare'
      path: '/lupo-di-mare'
      fullPath: '/lupo-di-mare'
      preLoaderRoute: typeof LupoDiMareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-nova': {
      id: '/dj-nova'
      path: '/dj-nova'
      fullPath: '/dj-nova'
      preLoaderRoute: typeof DjNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DjNovaRoute: DjNovaRoute,
  ExperienceRoute: ExperienceRoute,
  FaqRoute: FaqRoute,
  LupoDiMareRoute: LupoDiMareRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
